import { StyleSheet } from 'react-native';
import { moderateScale, scale, verticalScale } from 'react-native-size-matters';
import { Theme } from '../../libs';

const getStyles = colors =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#3E64FF',
    },
    header: {
      paddingHorizontal: scale(20),
      paddingTop: verticalScale(40),
      paddingBottom: verticalScale(30),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    profileSection: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    avatarContainer: {
      width: scale(80),
      height: scale(80),
      borderRadius: scale(40),
      backgroundColor: '#E0E0E0',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: Theme.colors.white,
    },
    avatar: {
      width: '100%',
      height: '100%',
      borderRadius: scale(40),
    },
    plusButton: {
      position: 'absolute',
      bottom: 0,
      right: scale(-5),
      width: scale(26),
      height: scale(26),
      borderRadius: scale(13),
      backgroundColor: Theme.colors.white,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    plusText: {
      color: '#3E64FF',
      fontSize: moderateScale(18),
      fontWeight: '700',
    },
    userInfo: {
      marginLeft: scale(15),
      flex: 1,
    },
    companyName: {
      color: Theme.colors.white,
      fontSize: moderateScale(18),
      fontWeight: '700',
    },
    userEmail: {
      color: 'rgba(255, 255, 255, 0.8)',
      fontSize: moderateScale(14),
      marginTop: verticalScale(2),
    },
    headerActions: {
      alignItems: 'flex-end',
    },
    notificationContainer: {
      width: scale(40),
      height: scale(40),
      borderRadius: scale(20),
      backgroundColor: Theme.colors.white,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: verticalScale(10),
    },
    notificationBadge: {
      position: 'absolute',
      top: scale(-5),
      right: scale(-5),
      backgroundColor: '#FF3B30',
      borderRadius: scale(8),
      paddingHorizontal: scale(5),
      height: scale(16),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: Theme.colors.white,
    },
    badgeText: {
      color: Theme.colors.white,
      fontSize: moderateScale(10),
      fontWeight: '700',
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    logoutText: {
      color: Theme.colors.white,
      fontSize: moderateScale(14),
      fontWeight: '600',
      marginLeft: scale(5),
    },
    contentCard: {
      flex: 1,
      backgroundColor: Theme.colors.white,
      borderTopLeftRadius: scale(30),
      borderTopRightRadius: scale(30),
      paddingTop: verticalScale(20),
    },
    tabBar: {
      flexDirection: 'row',
      marginHorizontal: scale(20),
      backgroundColor: '#F5F7FF',
      borderRadius: scale(25),
      padding: scale(4),
      marginBottom: verticalScale(20),
      borderWidth: 1,
      borderColor: '#E8EDFF',
    },
    tab: {
      flex: 1,
      height: verticalScale(40),
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: scale(20),
    },
    activeTab: {
      backgroundColor: '#E8EDFF',
    },
    tabText: {
      fontSize: moderateScale(12),
      color: '#9E9E9E',
      fontWeight: '600',
    },
    activeTabText: {
      color: '#3E64FF',
    },
    mainContent: {
      flex: 1,
      paddingHorizontal: scale(20),
    },
    bgImage: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      opacity: 0.1,
    },
    sectionTitle: {
      fontSize: moderateScale(20),
      fontWeight: '700',
      color: '#000',
      textAlign: 'center',
      marginBottom: verticalScale(15),
    },
    videoPlaceholder: {
      width: '100%',
      height: verticalScale(180),
      backgroundColor: '#1A1A1A',
      borderRadius: scale(15),
      borderWidth: 2,
      borderColor: '#3E64FF',
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    videoText: {
      color: '#3E64FF',
      fontSize: moderateScale(16),
      fontWeight: '500',
    },
    placeholderLine: {
      position: 'absolute',
      width: '120%',
      height: 2,
      backgroundColor: '#3E64FF',
      opacity: 0.3,
    },
    subTitle: {
      fontSize: moderateScale(18),
      fontWeight: '700',
      color: '#000',
      textAlign: 'center',
      marginTop: verticalScale(20),
      marginBottom: verticalScale(10),
    },
    description: {
      fontSize: moderateScale(14),
      color: '#666',
      textAlign: 'center',
      lineHeight: moderateScale(20),
      paddingHorizontal: scale(10),
    },
    scrollContent: {
      paddingBottom: verticalScale(40),
    },
  });

export default getStyles;
