import { StyleSheet, Platform } from 'react-native';
import { moderateScale, scale } from 'react-native-size-matters';
import { Theme } from '../../../libs';

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(18),
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
  card: {
    width: '100%',
    maxWidth: moderateScale(380),
    maxHeight: '78%',
    backgroundColor: '#1A1A1C',
    borderRadius: moderateScale(24),
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.45,
        shadowRadius: 24,
      },
      android: { elevation: 16 },
    }),
  },
  headerGradient: {
    paddingTop: moderateScale(16),
    paddingBottom: moderateScale(16),
    paddingHorizontal: moderateScale(18),
  },
  closeButton: {
    position: 'absolute',
    top: moderateScale(14),
    right: moderateScale(14),
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(16),
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  closeIcon: {
    color: '#fff',
    fontSize: moderateScale(14),
    fontWeight: '700',
    lineHeight: moderateScale(16),
  },
  headerContent: {
    alignItems: 'center',
    paddingTop: moderateScale(4),
  },
  alertIconCircle: {
    width: moderateScale(48),
    height: moderateScale(48),
    borderRadius: moderateScale(24),
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: moderateScale(8),
  },
  alertIcon: {
    fontSize: moderateScale(24),
  },
  headerTitle: {
    fontSize: moderateScale(20),
    fontWeight: '800',
    color: '#fff',
    marginBottom: moderateScale(4),
    letterSpacing: 0.3,
  },
  headerSubtitle: {
    fontSize: moderateScale(12),
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: moderateScale(17),
    paddingHorizontal: moderateScale(10),
    marginBottom: moderateScale(8),
  },
  trendPill: {
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    paddingHorizontal: moderateScale(14),
    paddingVertical: moderateScale(6),
    borderRadius: moderateScale(20),
  },
  trendPillText: {
    color: '#fff',
    fontSize: moderateScale(12),
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  bodyScroll: {
    flexGrow: 0,
  },
  bodyContent: {
    paddingHorizontal: moderateScale(16),
    paddingTop: moderateScale(14),
    paddingBottom: moderateScale(4),
  },
  scoreSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: moderateScale(12),
    backgroundColor: '#242426',
    borderRadius: moderateScale(14),
    padding: moderateScale(10),
  },
  scoreRing: {
    width: moderateScale(60),
    height: moderateScale(60),
    borderRadius: moderateScale(30),
    borderWidth: moderateScale(3),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: moderateScale(10),
  },
  scoreInner: {
    alignItems: 'center',
  },
  scoreNumber: {
    fontSize: moderateScale(22),
    fontWeight: '800',
    lineHeight: moderateScale(26),
  },
  scoreMax: {
    fontSize: moderateScale(11),
    color: Theme.colors.grey,
    fontWeight: '600',
  },
  scoreMeta: {
    flex: 1,
  },
  scoreMetaLabel: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: Theme.colors.white,
    marginBottom: moderateScale(4),
  },
  scoreMetaHint: {
    fontSize: moderateScale(10),
    color: Theme.colors.grey,
    lineHeight: moderateScale(14),
    marginBottom: moderateScale(6),
  },
  progressTrack: {
    height: moderateScale(6),
    backgroundColor: '#3A3A3C',
    borderRadius: moderateScale(3),
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: moderateScale(3),
  },
  metricsRow: {
    flexDirection: 'row',
    gap: moderateScale(8),
    marginBottom: moderateScale(8),
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#242426',
    borderRadius: moderateScale(12),
    padding: moderateScale(10),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  metricIcon: {
    fontSize: moderateScale(16),
    marginBottom: moderateScale(4),
  },
  metricLabel: {
    fontSize: moderateScale(10),
    color: Theme.colors.grey,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: moderateScale(3),
  },
  metricValue: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: Theme.colors.white,
  },
  insightCard: {
    backgroundColor: 'rgba(134, 174, 18, 0.08)',
    borderRadius: moderateScale(12),
    padding: moderateScale(10),
    marginTop: moderateScale(4),
    marginBottom: moderateScale(8),
    borderWidth: 1,
    borderColor: 'rgba(134, 174, 18, 0.22)',
  },
  insightHeader: {
    marginBottom: moderateScale(4),
  },
  insightBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(134, 174, 18, 0.2)',
    paddingHorizontal: moderateScale(10),
    paddingVertical: moderateScale(4),
    borderRadius: moderateScale(8),
  },
  insightBadgeText: {
    fontSize: moderateScale(10),
    fontWeight: '800',
    color: Theme.colors.secondary,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  insightText: {
    fontSize: moderateScale(12),
    color: Theme.colors.text,
    lineHeight: moderateScale(18),
  },
  tipCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#2C2C2E',
    borderRadius: moderateScale(10),
    padding: moderateScale(10),
    gap: moderateScale(8),
  },
  tipEmoji: {
    fontSize: moderateScale(18),
    marginTop: moderateScale(1),
  },
  tipText: {
    flex: 1,
    fontSize: moderateScale(12),
    color: Theme.colors.text,
    lineHeight: moderateScale(18),
  },
  tipHighlight: {
    color: Theme.colors.secondary,
    fontWeight: '700',
  },
  footer: {
    paddingHorizontal: moderateScale(16),
    paddingTop: moderateScale(10),
    paddingBottom: moderateScale(14),
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: '#1A1A1C',
    alignItems: 'stretch',
    width: '100%',
  },
  footerActions: {
    width: '100%',
    alignSelf: 'stretch',
  },
  primaryButton: {
    backgroundColor: Theme.colors.secondary,
    borderRadius: moderateScale(12),
    paddingVertical: moderateScale(2),
    height: moderateScale(46),
    width: '100%',
    maxWidth: '100%',
    alignSelf: 'stretch',
  },
  snoozeButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    paddingVertical: moderateScale(8),
    marginTop: moderateScale(2),
  },
  snoozeText: {
    fontSize: scale(13),
    color: '#8E8E93',
    fontWeight: '600',
  },
});

export default styles;
