import { StyleSheet } from 'react-native';
import { moderateScale, scale, verticalScale } from 'react-native-size-matters';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#3E64FF',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  subHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  subButton: {
    flex: 1,
    backgroundColor: '#3E64FF',
    paddingVertical: verticalScale(12),
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderColor: '#FFFFFF',
  },
  subButtonText: {
    color: '#FFFFFF',
    fontSize: moderateScale(12),
    fontWeight: 'bold',
    textAlign: 'center',
  },
  rfqIdHeader: {
    backgroundColor: '#F1F5F9',
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(15),
    borderBottomWidth: 1,
    borderColor: '#CBD5E1',
  },
  rfqIdText: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: '#1E293B',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  headerCell: {
    borderRightWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rotatedHeaderCell: {
    width: scale(40),
    paddingTop: verticalScale(20),
    justifyContent: 'flex-start',
  },
  rotatedHeaderText: {
    fontSize: moderateScale(9),
    color: '#64748B',
    fontWeight: 'bold',
    transform: [{ rotate: '-90deg' }],
    width: scale(120),
    textAlign: 'center',
    position: 'absolute',
    top: verticalScale(35),
    right: scale(-40),
  },
  headerIconContainer: {
    marginTop: verticalScale(58),
    alignItems: 'center',
    marginBottom: verticalScale(5),
  },
  statusHeaderCell: {
    width: scale(40),
    paddingVertical: verticalScale(10),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusLabelText: {
    fontSize: moderateScale(9),
    fontWeight: 'bold',
    color: '#1E293B',
    transform: [{ rotate: '-90deg' }],
    width: scale(40),
    textAlign: 'center',
    marginTop: verticalScale(35),
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  inboxCell: {
    width: scale(110),
    padding: scale(8),
    borderRightWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  miniCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: scale(10),
    padding: scale(10),
    borderWidth: 1,
    borderColor: '#E2E8F0',
    width: '100%',
    alignItems: 'center',
    marginBottom: verticalScale(8),
  },
  cardHeaderIcons: {
    flexDirection: 'row',
    gap: scale(5),
    marginBottom: verticalScale(5),
  },
  supplierMiniName: {
    fontSize: moderateScale(12),
    fontWeight: 'bold',
    color: '#1E293B',
    textAlign: 'center',
  },
  moreInfoButton: {
    backgroundColor: '#3E64FF',
    borderRadius: scale(5),
    paddingVertical: verticalScale(8),
    width: '100%',
    alignItems: 'center',
  },
  moreInfoText: {
    color: '#FFFFFF',
    fontSize: moderateScale(11),
    fontWeight: 'bold',
  },
  selectionCell: {
    width: scale(40),
    borderRightWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectorsCell: {
    flex: 1,
    borderRightWidth: 1,
    borderColor: '#E2E8F0',
  },
  sectorItem: {
    height: verticalScale(40),
    justifyContent: 'center',
    paddingLeft: scale(8),
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  sectorText: {
    fontSize: moderateScale(12),
    color: '#1E293B',
  },
  statusChoicesCell: {
    width: scale(40),
    borderRightWidth: 1,
    borderColor: '#E2E8F0',
  },
  statusChoiceRow: {
    height: verticalScale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  selectionCircle: {
    width: scale(16),
    height: scale(16),
    borderRadius: scale(8),
    borderWidth: 1.5,
    borderColor: '#64748B',
  },
  selectionCircleActive: {
    backgroundColor: '#3E64FF',
    borderColor: '#3E64FF',
  },
});

export default styles;
